%% Function to rotate  wing coodinate
%  Created by T.Nonomura 2019.02.23
%  you can change bar length at variable "ndigits"
%  INPUT  : file name : file is generated by 
%  http://airfoiltools.com/airfoil/naca4digit?MNaca4DigitForm%5Bcamber%5D=0&MNaca4DigitForm%5Bposition%5D=0&MNaca4DigitForm%5Bthick%5D=15&MNaca4DigitForm%5BnumPoints%5D=200&MNaca4DigitForm%5BcosSpace%5D=0&MNaca4DigitForm%5BcosSpace%5D=1&MNaca4DigitForm%5BcloseTe%5D=0&yt0=Plot
%           
%  OUTPUT : display the progress bar in the command window

%% Main Code
function [x,y] = F_rotatewing(x,y,a,ac)
   xmin=min(x);
   xmax=max(x);
   x=(x-xmin)./(xmax-xmin)-ac;
   y=(y     )./(xmax-xmin);
   xnew= x.*cos(a/180*pi)+y.*sin(a/180*pi)+ac;
   ynew=-x.*sin(a/180*pi)+y.*cos(a/180*pi);
   %check 
%    figure(333)
%    plot(xnew,ynew)
   x=xnew;
   y=ynew;
end